### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by iSanechek** [brunocvcunha/instagram4j#1]
![screenshot from 2017-02-06 19 23 45](https://cloud.githubusercontent.com/assets/1894596/22653132/0cf18e56-eca2-11e6-892c-ed079d846430.png)

**Comment by brunocvcunha** [comment]
Hi!

Thanks for pinging me.

I started the project this weekend, and I'm still deploying everything, and it will make to Maven Central soon.

You can get some snapshots [here](https://oss.sonatype.org/content/repositories/snapshots/org/brunocvcunha/instagram4j/instagram4j/1.0-SNAPSHOT/), but I strongly recommend building from the sources at this time:

```
git clone https://github.com/brunocvcunha/instagram4j
cd instagram4j
mvn clean install
```

**Comment by iSanechek** [comment]
Hi @brunocvcunha. 
it's me again.) I have a new problem
**class file for org.apache.http.client.ClientProtocolException not found**
this problem is relevant for **snapshots**  and for **clean install** version .

**Comment by brunocvcunha** [comment]
Are you using the project as a dependency of your project, or as a Maven dependency?

If you want to add the JAR in your project, there are a lot of dependencies that you need to bring, that's why I always recommend to use Maven. In case you're having trouble, I can create a sample app that uses the API and submit as an example later. 

But in short, if you create a Maven project and add this as a dependency:

```
<dependency>
  <groupId>org.brunocvcunha.instagram4j</groupId>
  <artifactId>instagram4j</artifactId>
  <version>1.0-SNAPSHOT</version>
</dependency>
```

All the project dependencies should come together.

**Comment by brunocvcunha** [comment]
@iSanechek 

I'm attaching a sample project.
You should be able to run it using maven as well:

`mvn exec:java -Dexec.mainClass="org.brunocvcunha.instagram.manager.InstagramLikerPrivate"   -Dexec.classpathScope="compile" -Dexec.args="{myusername} {mypassword}"`

[instagram-sample-project.zip](https://github.com/brunocvcunha/instagram4j/files/756345/instagram-sample-project.zip)

**Comment by iSanechek** [comment]
@brunocvcunha oh... My bad. 
I used just as a jar file without the dependencies. 
And now Maven way and works perfectly. Thank you very much for the answers.)

**Comment by BenZeuner** [comment]
Hi, 
I got the same error
Error:(16, 40) java: cannot access org.apache.http.client.ClientProtocolException
  class file for org.apache.http.client.ClientProtocolException not found
even when using Maven:
<dependencies>
        <dependency>
            <groupId>org.brunocvcunha.instagram4j</groupId>
            <artifactId>instagram4j</artifactId>
            <version>1.13</version>
        </dependency>
    </dependencies>

Has something changed in the meantime? Unfortunately, I'm not that familiar with IntelliJ and Maven. But the POM is valid and dependencies where received. I get this error when building my project in this line: 
InstagramLoginResult login = instagram.login();

**Comment by BenZeuner** [comment]
> Hi,
> I got the same error
> 
> ```
> Error:(16, 40) java: cannot access org.apache.http.client.ClientProtocolException
>   class file for org.apache.http.client.ClientProtocolException not found
> ```
> 
> even when using Maven:
> 
> ```
> <dependencies>
>         <dependency>
>             <groupId>org.brunocvcunha.instagram4j</groupId>
>             <artifactId>instagram4j</artifactId>
>             <version>1.13</version>
>         </dependency>
>     </dependencies>
> ```
> 
> Has something changed in the meantime? Unfortunately, I'm not that familiar with IntelliJ and Maven. But the POM is valid and dependencies where received. I get this error when building my project in this line:
> `InstagramLoginResult login = instagram.login();`

It was my own mistake. I created a Maven project from scratch and now everything is working :) Thx
