### ISSUE TITLE
Cannot find or load main class

### ISSUE THREAD

**Issue by colpomatteo** [brunocvcunha/instagram4j#100]
After adding Lombok jar from maven i get this error:
Error: Can't find or load main class
/Users/*****/Library/Caches/NetBeans/8.2/executor-snippets/run.xml:53: Java returned: 1

How can i fix this?

**Comment by coolnickname** [comment]
Seems unrelated. Please close.

**Comment by anatechng** [comment]
You installed the wrong jar file, the correct jar file is lombok-1.16.16
