### ISSUE TITLE
Conflicting Internal Code (org.apache.httpcomponents:httpclient:4.5.2)

### ISSUE THREAD

**Issue by RonArel** [brunocvcunha/instagram4j#105]
I made a Blank hello world activity and I used:
`compile 'org.brunocvcunha.instagram4j:instagram4j:1.6
`
To access the API. 

I then get this error...

```
Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.5.2 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
```

What is wrong?

**Comment by brunocvcunha** [comment]
There are some issues here that mention limitations for Android. There's another project based on this that was created to support Android: https://github.com/charlieAndroidDev/Instagram4Android

**Comment by RonArel** [comment]
I posted an issue on that Repository, too. Please help me out by checking it out.
