### ISSUE TITLE
After using, sponsored language changes to Taiwanese?

### ISSUE THREAD

**Issue by ozankaraali** [brunocvcunha/instagram4j#126]
Hey, I think after using this library the sponsored ads become Taiwanese or something.
If anyone has the same effect on his/her account, please let me know and I will try to understand if it is only me or it is about the API keys that extracted.
Thanks.

**Comment by brunocvcunha** [comment]
I didn't have this issue.
Let's wait to hear from someone else.

**Comment by ozankaraali** [comment]
Yeah, I didn't think so, however it's a doubt that I did a rageshake, reported wrong ad language, it turned English, then I used it again and it swapped to Taiwanese again, then I changed whole device info with mgp25's and seems it gets more stable. However still I am not sure about this is about API or friends that I have, so I wanted to ask it to other users. Thank you for labeling as question and have a good day.
