### ISSUE TITLE
proper usage to delete photo

### ISSUE THREAD

**Issue by jvogit** [brunocvcunha/instagram4j#132]
What is the proper usage for deleting photo? I have tried using delete media request but i do not know what to place in for media id or im doing it properly?

**Comment by Mykke24** [comment]
Example of a media ID:
https://www.instagram.com/p/BgmG57Ej4GM

press CTRL+U in your browser and open the source code, search for "instagram://media?id="
this ID is the media ID you need to delete a media

or simply use .getMediaId()

**Comment by jvogit** [comment]
#139

**Comment by jvogit** [comment]
#139
