### ISSUE TITLE
Read Direct Messages

### ISSUE THREAD

**Issue by krismorte** [brunocvcunha/instagram4j#144]
I forked the project and start this part but I'm stucked in the inbox paging

```
InstagramGetInboxRequest i = new InstagramGetInboxRequest();
			InstagramInboxResult s = instagram.sendRequest(i);
			
			
			//System.out.println("Size1 " + s.seq_id);
			System.out.println("Size1 " + threads.size());
			for (InstagramInboxThread t : threads) {
				System.out.println("inv " + t.inviter.full_name);
				for (InstagramUser u : t.users) {
					System.out.println("u " + u.getFull_name());
				}

				for (InstagramInboxThreadItem it : t.items) {
					if (it.item_type.equals("reel_share")) {
						System.out.println("reel_share");
						System.out.println("it " + it.reel_share.text);
						System.out.println("it " + it.reel_share.media.pk);
					} else {
						System.out.println("other");
						System.out.println("it " + it.item_type);
						System.out.println("it " + it.like);
					}
				}

			}

```

This code above bring me the last 20 Inbox Direct and the last message of all but I don't know whats is the url parameter to pass the cursorId like I read in this link

https://github.com/mgp25/Instagram-API/blob/master/src/Request/Direct.php

**Comment by krismorte** [comment]
#154

**Comment by MuslimArsakaev** [comment]
hello gues

the code that I'll share with you does: prints 20 messages from one chat room. It total performs in 20 chat rooms

#    InstagramInboxResult inbox = instagram4j.sendRequest(new InstagramGetInboxRequest());

    AtomicInteger counter = new AtomicInteger();
    for (InstagramInboxThread thread : inbox.getInbox().getThreads()) {
      thread.getItems().forEach(instagramInboxThreadItem -> {

        System.out.println("chat id " + counter.incrementAndGet());
        try {
          InstagramInboxThreadResult inboxThread = instagram4j
                  .sendRequest(new InstagramGetInboxThreadRequest(thread.getThread_id(), thread.getOldest_cursor()));
          
          AtomicInteger counter1 = new AtomicInteger();

          inboxThread.getThread().getItems().forEach(instagramInboxThreadItem1 -> {
            System.out.println(counter1.incrementAndGet() + " instagramInboxThreadItem1 " + instagramInboxThreadItem1.getText());
          });

        } catch (IOException e) {
          e.printStackTrace();
        }
      });
    }

**Comment by lusicsmusics1** [comment]
> hello friends
> 
> the code that I'll share with you does: prints 20 messages from one chat room. It total performs in 20 chat rooms
> 
> # InstagramInboxResult inbox = instagram4j.sendRequest(new InstagramGetInboxRequest());
> ```
> AtomicInteger counter = new AtomicInteger();
> for (InstagramInboxThread thread : inbox.getInbox().getThreads()) {
>   thread.getItems().forEach(instagramInboxThreadItem -> {
> 
>     System.out.println("chat id " + counter.incrementAndGet());
>     try {
>       InstagramInboxThreadResult inboxThread = instagram4j
>               .sendRequest(new InstagramGetInboxThreadRequest(thread.getThread_id(), thread.getOldest_cursor()));
>       
>       AtomicInteger counter1 = new AtomicInteger();
> 
>       inboxThread.getThread().getItems().forEach(instagramInboxThreadItem1 -> {
>         System.out.println(counter1.incrementAndGet() + " instagramInboxThreadItem1 " + instagramInboxThreadItem1.getText());
>       });
> 
>     } catch (IOException e) {
>       e.printStackTrace();
>     }
>   });
> }
> ```

how can we listen to more 20 threads chat and or listen to new incoming messages?
thanks
