### ISSUE TITLE
How get just the last post with feedResult and not all of feed?

### ISSUE THREAD

**Issue by spritrl** [brunocvcunha/instagram4j#155]
Helllo! I'm trying to get just the last post and not all of feed..

This my code :
`InstagramFeedResult userFeed = instagram.sendRequest(new InstagramUserFeedRequest(45818965));
				for(InstagramFeedItem feedResult : userFeed.getItems()) {
			    System.out.println(feedResult.getPk());
			}`

And my logs (all of feed) :
1746429899781946885
1696366809030967069
1686065053424238071
1660713727563813716
1654809678117248507
1647607091085398853
1509889454801573630
1495989159503706867
1490871493369630272
1490285791775002650
1466518855392049650
1463192776614951261
1457219864573517392
1449705088280006377
1427832556484637082
1420238180917073016
1388994315955366481
1363439357063551365

I just want "1746429899781946885"
Help me please.

**Comment by egold555** [comment]
Just get the 0'th item in the array, that is the most recent post.

**Comment by egold555** [comment]
InstagramFeedResult userFeed = instagram.sendRequest(new InstagramUserFeedRequest(2021969959));
InstagramFeedItem item = userFeed.getItems().get(0);
