### ISSUE TITLE
Likers

### ISSUE THREAD

**Issue by jrvansuita** [brunocvcunha/instagram4j#17]
How can I get the users that liked a post? I'm trying to know who liked the post.
In my exemple, `feedItem.getLikers();` always returns null;

My code:
```java
InstagramUser user = instapi.sendRequest(new InstagramSearchUsernameRequest(userName)).getUser();

if (user != null) {
   System.out.println("User found: " + user.getUsername() + ", Followers: " + user.getFollower_count() + ", Following: " + user.getFollowing_count());

   InstagramFeedResult userFeedResult = instapi.sendRequest(new InstagramUserFeedRequest(user.getPk()));
   for (InstagramFeedItem feedItem : userFeedResult.getItems()) {
       feedItem.getLikers();
   }
}
```

**Comment by mmotorniy** [comment]
Is there any update with this issue?

**Comment by iSanechek** [comment]
I think [here](https://github.com/brunocvcunha/instagram4j/blob/master/src/main/java/org/brunocvcunha/instagram4j/requests/InstagramLikeRequest.java) `"media/" + mediaId + "/like/"` to replace on `"media/" + mediaId + "/likers/".  It's supposed to work. Need to test.

**Comment by jrvansuita** [comment]
Ok, so it needs be implemented!

**Comment by brunocvcunha** [comment]
Hi guys,

I pushed a new request to handle this endpoint: `InstagramGetMediaLikersRequest`
It's still on master, I will deploy a new version to Maven central in a few days.

@jrvansuita @mmotorniy
