### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by dparafilo** [brunocvcunha/instagram4j#19]
Is there some rate limits on API calls? How many requests I can make per hour/day to avoid getting banned?

**Comment by captainJackBard** [comment]
I'm posting 10 pictures per hour and I'm not getting banned, Anything more than that I always get banned for 24 hours. I'm not sure about other endpoints, I'm only uploading pictures.

**Comment by brunocvcunha** [comment]
Instagram is very smart, and if you want to automate tasks, I think the main point here is trying to behave like a user.
There are many details depending on the action, but other than having a reasonable number of calls, it's important also to intervals between the actions, and also avoid to run any process on a 24/7 basis.

**Comment by krismorte** [comment]
There's no way to know what are the Rate limits?

**Comment by tayfunyasar** [comment]
Is there a way to limit user's call? via api?

**Comment by fabriziomorello** [comment]
Hey @brunocvcunha , any update on this? It should be useful to have an idea about limits. In particular, I'm interested id there is any limitation on GET operations.
