### ISSUE TITLE
How can I send a private message?

### ISSUE THREAD

**Issue by oemluuu** [brunocvcunha/instagram4j#201]
Hey, I am new to this API and I somehow couldn't figure out how to send a private message.

**Comment by KorexDevelopment** [comment]
InstagramDirectShareRequest request = InstagramDirectShareRequest.builder(InstagramDirectShareRequest.ShareType.MEDIA, recipients).mediaId(mediaId).message("An example :)").build();
this.instagram.sendRequest(request);

Just an example, I think it is obvious what the code does.
The List<String> recipients is consiting of user.getPk() as String.

**Comment by oemluuu** [comment]
Thank you!
