### ISSUE TITLE
Missing likers in InstagramGetMediaLikersRequest

### ISSUE THREAD

**Issue by Athamax** [brunocvcunha/instagram4j#227]
Fetching likers with `InstagramGetMediaLikersRequest` only returns some of the likers.

For example, on a post with 5k+ likers, I only get 986.
With the comments, I could use `next_max_id` to go around this issue, but the constructor for  `InstagramGetMediaLikersRequest`  doesn't support a max id. 

I can only do  `InstagramGetMediaLikersRequest(media_id)` and get an incomplete result.

How can I get a full list?

**Comment by threadbuilder** [comment]
This function is not supported by IG.
The link shows the answer.
https://github.com/huttarichard/instagram-private-api/issues/70

**Comment by JoaoGarcez** [comment]
I have the same problem i can onky get +-1000 likers. It is possible to change the constructor to suport nextmaxID VARIABLE ?

**Comment by Athamax** [comment]
> I have the same problem i can onky get +-1000 likers. It is possible to change the constructor to suport nextmaxID VARIABLE ?

No, I eventually gave up as I found out that Instagram doesn't show more than about 1000 likers on the browser, so there's no way the private API could get them. There is no "show more" button, so there's no "next_max_id".
