### ISSUE TITLE
upload image issue

### ISSUE THREAD

**Issue by xiaohunsdt** [brunocvcunha/instagram4j#236]
Hi, everyone! I uploaded some photoes by instagram4j. Upload is successful, but after 20 minutes,the account was blocked.  who can help me to solve this problem !?? thank everyone!

**Comment by xiaohunsdt** [comment]
PS: my photoes size is 1080 * 1080. and all of photoes below 120kb!!

**Comment by xiaohunsdt** [comment]
And I used proxy to upload photos.

**Comment by brunocvcunha** [comment]
The block could be caused by many reasons, such as the type of access that you did, a speed which you executed or even a proxy that was blacklisted by Instagram. I don't think it has to do with the project itself, as many are using without problems.
