### ISSUE TITLE
How it works? private api

### ISSUE THREAD

**Issue by jvitorr** [brunocvcunha/instagram4j#238]
Hello, 

How it works, there is a instagram private api?
Why there is instagram private api and not for facebook? 
This works like selenium webdriver for mobile?

It is only doubt lol

**Comment by brunocvcunha** [comment]
It simulates the way that the Instagram mobile app accesses the APIs. It's private because it's not publicly documented, and usually, the way to do it has to be figured out from reverse engineering of source code and/or monitoring network traffic.
