### ISSUE TITLE
How to know is a user follow me

### ISSUE THREAD

**Issue by TheMalloum** [brunocvcunha/instagram4j#241]
how to know if a user follow my compte

I searched in class "InstagramUser" and "InstagramUserSummary" but I didn't find it.

I have not choice to Get user followers (expensive).

Thanks

**Comment by TheMalloum** [comment]
how to know if a user follow my compte

I searched in class "InstagramUser" and "InstagramUserSummary" but I didn't find it.

I have not choice to Get user followers (expensive).

Thanks

**Comment by jcagz-iscteiul** [comment]
You can do something like this:

`InstagramSearchUsernameResult userResult = instagram.sendRequest(new InstagramSearchUsernameRequest("github"));

long key = userResult.getUser().getPk()

InstagramFriendshipStatus friendshipStatus = instagram.sendRequest(new InstagramGetFriendshipRequest(key));

System.out.println("I follow ? " + friendshipStatus.following);
System.out.println("Am i followed by?" + friendshipStatus.followed_by);`

**Comment by TheMalloum** [comment]
Hi @jcagz-iscteiul,

Thanks
