### ISSUE TITLE
How can you get a username with userID?

### ISSUE THREAD

**Issue by termxz** [brunocvcunha/instagram4j#256]
Anyone know??

**Comment by ItsGravix** [comment]
I need this too!

**Comment by b0nn13** [comment]
It's work for me
`public class App {
	private static final InstagramAuthenticatorFactory instaAuth = InstagramAuthenticatorFactory.getInstance();
	private static Instagram4j INSTAGRAM;

	public static void main(String[] args) {
		INSTAGRAM = instaAuth.connect("USER", "PASSWORD");
		try {
			InstagramSearchUsernameResult userResult = getUserData(668138693L);
			System.out.println("ID for " + userResult.getUser().getUsername() + " is " + userResult.getUser().getPk());
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	private static InstagramSearchUsernameResult getUserData(Long userId) throws ClientProtocolException, IOException {
		INSTAGRAM.login();
		InstagramSearchUsernameResult userResult = INSTAGRAM.sendRequest(new InstagramGetUserInfoRequest(userId));
		
		return userResult;
	}
}`

**Comment by termxz** [comment]
Solved, thanks.
