### ISSUE TITLE
disable log

### ISSUE THREAD

**Issue by ataafarin** [brunocvcunha/instagram4j#27]
Hi,
how can i disable instagram log?
I set setDebug to false but they are comming yet!

Thanks

**Comment by brunocvcunha** [comment]
The logging is based on log4j, so you could create a log4j.properties and set the level of instagram4j to WARN (or ERROR):

```
log4j.rootLogger=INFO,CONSOLE
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c %x - %m%n

log4j.logger.org.brunocvcunha.instagram4j=WARN
```

**Comment by lxknvlk** [comment]
I have created such a file with specified contents in my project root directory, but it did not solve the problem

**Comment by jemand771** [comment]
#384
