### ISSUE TITLE
Connecting hanging won't time out

### ISSUE THREAD

**Issue by Cousin** [brunocvcunha/instagram4j#271]
Randomly after a while certain requests will just hang... forever.
![image](https://user-images.githubusercontent.com/8135809/52972759-dba3ec00-3389-11e9-9904-944323826203.png)
It has been stuck here literally over night.

Is there any way I could set some sort of connection/read time out?

**Comment by jamieses** [comment]
Issue happened to me too.

**Comment by Cousin** [comment]
Well I guess I fixed it... just put it inside a Future and set the timeout for it. Not really a direct fix but works for now.
