### ISSUE TITLE
Mute Story and Post for user

### ISSUE THREAD

**Issue by rodrigae** [brunocvcunha/instagram4j#274]
does the API support, muting a user story and posts?

**Comment by TheMalloum** [comment]
+1

**Comment by TheMalloum** [comment]
@rodrigae i do a pull request, I waiting that it will be accept and a next release. 
cc @brunocvcunha

**Comment by TheMalloum** [comment]
@brunocvcunha you can close this issue

**Comment by rodrigae** [comment]
@TheMalloum you have this already? I’ve been waiting for it, just finally started with the API.

**Comment by TheMalloum** [comment]
@rodrigae it's been in last release in 1.10 version.

**Comment by brunocvcunha** [comment]
Thanks @TheMalloum and @rodrigae. Closing
