### ISSUE TITLE
set Proxy

### ISSUE THREAD

**Issue by ataafarin** [brunocvcunha/instagram4j#28]
Is there anyway to set proxy on connection?
I tested below code but no luck    
```
    System.setProperty("http.proxyHost", host);
    System.setProperty("http.proxyPort", port);
```
It seems `Instagram4j` class need this function(like php version).

Thanks In Advance

**Comment by BondarenkoEvgeny** [comment]
Instagram4j uses the apache http client.
Instagram.getClient () returns an instance of DefaultHttpClient, in which you can configure the use of the proxy

**Comment by ataafarin** [comment]
I was using socks,
solved using :
```
    System.setProperty("socksProxyHost", "127.0.0.1");
    System.setProperty("socksProxyPort", "9150");
```

**Comment by brunocvcunha** [comment]
Hi, guys!

Yes, you can either configure the environment properties or change the configs in the DefaultHttpClient created inside the `setup()` method.
