### ISSUE TITLE
Auto accept friend requests

### ISSUE THREAD

**Issue by gsegatori** [brunocvcunha/instagram4j#299]
How can we get the list of the user pending request and accept them?

**Comment by coolnickname** [comment]
I'm also curious but afraid it's not implemented yet

**Comment by gsegatori** [comment]
I implemented it, you have to extend it

**Comment by coolnickname** [comment]
What's the request called?

**Comment by gsegatori** [comment]
friendships/approve/
friendships/pending/

**Comment by coolnickname** [comment]
If you already have it could you make a PR?
