### ISSUE TITLE
It is possible to get story viewers?

### ISSUE THREAD

**Issue by MrGian** [brunocvcunha/instagram4j#314]

**Comment by DanielePancottini** [comment]
At the moment there isn't a class that handle your request, I guess. But to get stories insight Instagram API provide an endpoint to receive the information required: "/media/insights". You can try to develop a class that handle that or if I will find time, I will try to implement that by myself

**Comment by vadimTovstik** [comment]
that would be very cool. I also need the "who watched the story" method

**Comment by DanielePancottini** [comment]
I've just finished yesterday to develop the request for story user. I'm doing some test and then I will make a PR

**Comment by vadimTovstik** [comment]
This will help me a lot.

**Comment by DanielePancottini** [comment]
@vadimTovstik Ok, I've done a PR about story viewers, try to test methods and let me know. Everything should work
