### ISSUE TITLE
Why so many requests

### ISSUE THREAD

**Issue by Soldrakon** [brunocvcunha/instagram4j#316]
Why do we have to make a request to get some basic information about the account?

**Comment by jemand771** [comment]
because that is how the instagram api is designed. the library just gives you an easier way to talk to it
do you need help with anything specific?

**Comment by brunocvcunha** [comment]
Right! It's just that Instagram4j tries to make the same requests that are done on the app. Sometimes you need to slow down, the API is not intended for robots, but for real users to navigate through the interface.
