### ISSUE TITLE
Deprication of Instagram API

### ISSUE THREAD

**Issue by bvn13** [brunocvcunha/instagram4j#325]
According to https://developers.facebook.com/blog/post/2018/10/31/instagram-graph-api-hashtag-search-launch/ deprication of Instagram API is started since December 11, 2018.

Do you plan to maintain new API?

**Comment by tayfunyasar** [comment]
I also wonder it.

**Comment by jemand771** [comment]
This is related to the public instagram API (which was kinda trash anyway)
Instagram4j however accesses the endpoints of the internal (private) API used by the official android app.
No worries :)
