### ISSUE TITLE
Tagged users in pictures

### ISSUE THREAD

**Issue by HectorHumanes** [brunocvcunha/instagram4j#329]
Hi all, I'm triying to get the users tagged in a picture from a InstagramFeedItem using the method getUsertags(). Sometimes the size of the returned array is zero (that I supose means nobody tagged) and sometimes the size is 1. In the last case, if I check the element of the array I get an object like this: `InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@5cc69cfe, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)`

If I check the picture in Instagram I see there is one or more people tagged in the picture. Am I doing something wrong or it's a bug?

In case anybody have a working code about this I'll be very pleased if you share an example.

Thanks and congratulations for the amazing work done @brunocvcunha

**Comment by DanielePancottini** [comment]
@HectorHumanes can you post the entire code? I will try to reproduce your issue in the afternoon and I will let you know

**Comment by HectorHumanes** [comment]
Yeah sure!
`Instagram4j instagram = Instagram4j.builder().username("XXXX").password("XXXXXX").build();
instagram.setup();
instagram.login();
InstagramSearchUsernameResult userResult = instagram
				.sendRequest(new InstagramSearchUsernameRequest("mis_fotos_de_madrid")); //It's just an example account. You can change it
InstagramFeedResult result = instagram.sendRequest(new InstagramUserFeedRequest(userResult.getUser().getPk()));

for (InstagramFeedItem item : result.getItems()) {			
			System.out.println(item.getUsertags());
		}`

And the response I get from the for loop:
`[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@2f2bf0e2, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@25f9407e, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@1b28f282, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@16423501, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@4e4efc1b, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@7db534f2, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@2a76b80a, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@61d9efe0, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@a50b09c, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@2187fff7, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@4de025bf, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@11389053, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@560cbf1a, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@578524c3, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@7a11c4c7, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@4152d38d, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@5cc5b667, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]
[InstagramFeedUserTag(super=org.brunocvcunha.instagram4j.requests.payload.InstagramFeedUserTag@182f1e9a, user=null, position=[0.0, 0.0], start_time_in_video_in_sec=0.0, duration_in_video_in_sec=0.0)]`

Thank you very much for your help!

**Comment by jemand771** [comment]
Can confirm.
Issue is related to wrong object models. InstagramFeedItem and UserTag need modification. I'll do some testing and update you in a couple of hours.
This is what the response inside of InstagramFeedItem actually looks like (sorry for censoring out data, it's not my pic/account)
![Unbenannt](https://user-images.githubusercontent.com/19669567/58703770-14e8f080-83aa-11e9-99fe-d8a9304135ae.png)

**Comment by HectorHumanes** [comment]
Thank you very much guys!

**Comment by jemand771** [comment]
Got it working.
Please try to modify your `InstagramFeedItem` and create a new Container class as I did to fit the model in the picture.
(you can use https://github.com/jemand771/instagram4j/commit/0469ce349e55c4830f69055eb77b4ded8bcaa2ca for reference)
If it works for you, I'll open a PR and submit the changes later :)

**Comment by HectorHumanes** [comment]
I'm afraid I'm using the maven dependency, so I can't directly modify the core code of the library. On the other hand I see you have crearly identified the problem (and I you got working so I guess you got the solution as well) so I thing you should open the PR. 
Or maybe anyone else can test the solution and open the PR then?

**Comment by DanielePancottini** [comment]
@HectorHumanes I'm doing some test, the PR was already opened by @jemand771, maybe it will included on next release

**Comment by DanielePancottini** [comment]
@jemand771 I've done some tests and your fix works fine
