### ISSUE TITLE
Broken captions in InstagramUploadPhotoRequest

### ISSUE THREAD

**Issue by HectorHumanes** [brunocvcunha/instagram4j#342]
Hi all, 
It seems that since yesterday the InstagramUploadPhotoRequest doesn't accept captions. It's probably due to a change in the Instagram internal API. Can someone check if it's failing?

Sample not working code:
`public void publish() {		
		try {			
			URL url = new URL(/*IMAGE URL HERE*/);
			String caption = "This is a sample caption";
			instagram.sendRequest(new InstagramUploadPhotoRequest(url,caption));
		} catch (Exception e) {
			logger.error("Problem during post publication: "+e);
		} 		
	}`

PS: The code above was working until yesterday, so my guess is that something has crash behind the scenes

Thank you all!

**Comment by DanielePancottini** [comment]
@HectorHumanes Thanks for reporting this issue. I'm checking your code, I'll let you know very close 👍

**Comment by DanielePancottini** [comment]
@HectorHumanes your code is perfectly working, check the semicolon after caption declaration 😄

**Comment by HectorHumanes** [comment]
I'm checking the code with another IG account and it seems to work fine, so possible reasons:

1. This part of the API was temporally down o they were testing new API funcionalities with my account

2. I've got banned somehow just from writting captions in the pictures (idk if it's possible)

**Comment by HectorHumanes** [comment]
> 
> 
> @HectorHumanes your code is perfectly working, check the semicolon after caption declaration 😄

Thanks for the note, but this mistake is due to the code edition in Github post, not present in my code

**Comment by DanielePancottini** [comment]
@HectorHumanes I think there was a problem on the Instagram WS, caption problems were reported also by other users few days ago.

Anyway, now seems to be all solved, you shouldn't have others problems with caption. 😃
