### ISSUE TITLE
InstagramTimelineFeedRequest always fails

### ISSUE THREAD

**Issue by gamer818** [brunocvcunha/instagram4j#354]
All my attempts to get the timeline feed ends in `Reading InstagramFeedResult from {"message": "", "status": "fail"}`. Is there another way to get my feed/am I doing something wrong? Help is very much appreciated!

**Comment by HectorHumanes** [comment]
Can you post the code you are using?

**Comment by gamer818** [comment]
Sorry, here's the line I am using to send the feed request
`InstagramFeedResult timelineFeed = instagram.sendRequest(new InstagramTimelineFeedRequest());`

**Comment by HectorHumanes** [comment]
In my code the feeds requests are made like:

1. I search for the user I want the feed and get the PK of the user

2. Once I get the PK I make the request using this PK.

In code:

`InstagramSearchUsernameResult request = instagram.sendRequest(new InstagramSearchUsernameRequest("theUserNameYouWant"));
InstagramUser user = request.getUser();
InstagramFeedResult result = instagram.sendRequest(new InstagramUserFeedRequest(user.getPk()));
`
Notice that you may need to make multiple feed requests to get the full feed.

**Comment by gamer818** [comment]
@HectorHumanes I appreciate your help, but I'm trying to send an InstagramTimelineFeedRequest, not a InstagramUserFeedRequest. I'm trying to get the timeline of the user I'm logged in with, not the medias of a specific user.

**Comment by HectorHumanes** [comment]
Upss yes, true. So, i'm afraid I haven't any piece of code for timeline feed, sorry!
I will leave my previous answer in case someone find it useful for other operations

**Comment by gamer818** [comment]
The updated code @jvogit referenced fixes this issue and I will be closing this thread. Thanks a lot for all the help!

**Comment by tayfunyasar** [comment]
Its not merged yet. Why did you close it?
