### ISSUE TITLE
Get Media of special User

### ISSUE THREAD

**Issue by sinaghz** [brunocvcunha/instagram4j#36]
hi, 
is there any func to get my or a specific user's medias ?
Thanks

**Comment by sinaghz** [comment]
It only returns maximum 18 items, what should i do to return all of it ?

**Comment by brunocvcunha** [comment]
When you run the InstagramUserFeedRequest, you receive a InstagramFeedResult. This feed result has a field called next_max_id, just run another InstagramUserFeedRequest passing that ID as maxId and you can get the next set of medias.
