### ISSUE TITLE
Cannot get number of likes for comment

### ISSUE THREAD

**Issue by IslamNosser** [brunocvcunha/instagram4j#365]
When it will be available to retrieve the like count per comment?

**Comment by jemand771** [comment]
Somewhat-Duplicate to #92 (that's a pretty old issue so opening a new one was the right thing to do)

I'll look into this

**Comment by IslamNosser** [comment]
@jemand771 thanks for your support. You have any idea when this change will be available on maven repository?

**Comment by jemand771** [comment]
@IslamNosser You're welcome! I'm afraid I have bad news for you: As you may have noticed the [release schedule](https://github.com/brunocvcunha/instagram4j/releases) for this library is really inconsistent. Getting new changes merged and enough other new features (so it's even worth a new version) can take up to two months.
