### ISSUE TITLE
Unable to see metadatas on my stories

### ISSUE THREAD

**Issue by gss0** [brunocvcunha/instagram4j#372]
Hi,
i'm unable to view metadata about my stories. It only displays the image and an empty div with all the dimensions set (... x(0.5).y(0.5).height(0.5) ) . What am I doing wrong?

This is the code used:

```
Collection<StoryMetadata> metadatas = new ArrayList<StoryMetadata>();
StoryCountdown story_countdown = StoryCountdown.builder().text("Aste in scadenza !").end_ts(new SimpleDateFormat("dd-MM-yyyy HH:mm:ss").parse("10-09-2019 14:45:00").getTime() * 1000).x(0.5).y(0.5).height(0.5).build();
metadatas.add(story_countdown);
InstagramUploadStoryPhotoRequest req = new InstagramUploadStoryPhotoRequest(imageToUpload, metadatas);
InstagramConfigureStoryResult result = instagram.sendRequest(req);
```

As suggested from @jvogit I changed instagram constraints according to #359 without effect.
thanks

**Comment by jvogit** [comment]
Are you trying to get the story metadata when you send request for them? I've implemented getting the metadata in #352 (which needs the updated constants #359 )

**Comment by gss0** [comment]
I'm trying to publish a new story with metadatas...but only hashtags and mentions works

**Comment by gss0** [comment]
> > I'm trying to publish a new story with metadatas...but only hashtags and mentions works
> 
> It seems to work on my end. Hm.

Are you using the default branch (master v1.12) or modified branch !? I'm testing both versions with different instagram accounts and always i get the same result.... I can't see countdown, poll and question on my IG stories .
