### ISSUE TITLE
"400, Something went wrong" while posting photo

### ISSUE THREAD

**Issue by AleTassi** [brunocvcunha/instagram4j#393]
Hi,

I'm uploading a photo 

```
instagram.sendRequest(new InstagramUploadVideoRequest(post.getFile(), post.getDescription()));
```
I'm 100% sure that post.getFile() return a valid FIle and post.getDescription() return a non null String
and I'm getting this ugly error

```
2019-11-19 21:40:32 [scheduling-1] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest
2019-11-19 21:40:32 [scheduling-1] INFO  org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest  - URL Upload: https://i.instagram.com/api/v1/upload/photo/
2019-11-19 21:40:33 [scheduling-1] INFO  org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest  - Photo Upload result: 400, Something is wrong. Please check your input and try again.
2019-11-19 21:40:33 [scheduling-1] INFO  org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading InstagramConfigurePhotoResult from Something is wrong. Please check your input and try again.
2019-11-19 21:40:33.521 ERROR 4696 --- [   scheduling-1] a.tassinari.core.InstaService            : Unrecognized token 'Something': was expecting ('true', 'false' or 'null')
 at [Source: (String)"Something is wrong. Please check your input and try again."; line: 1, column: 10]

com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Something': was expecting ('true', 'false' or 'null')
 at [Source: (String)"Something is wrong. Please check your input and try again."; line: 1, column: 10]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804) ~[jackson-core-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703) ~[jackson-core-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853) ~[jackson-core-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1899) ~[jackson-core-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757) ~[jackson-core-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141) ~[jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000) ~[jackson-databind-2.9.9.jar:2.9.9]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004) ~[jackson-databind-2.9.9.jar:2.9.9]
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:141) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:111) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.parseResult(InstagramUploadPhotoRequest.java:171) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.execute(InstagramUploadPhotoRequest.java:106) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.execute(InstagramUploadPhotoRequest.java:44) ~[instagram4j-1.11.jar:na]
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:281) ~[instagram4j-1.11.jar:na]
	at a.tassinari.core.InstaService.postPhoto(InstaService.java:67) [classes/:na]
	at a.tassinari.core.InstaService.postFile(InstaService.java:44) [classes/:na]
	at a.tassinari.core.Scheduler.schedule(Scheduler.java:41) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.0.M3.jar:5.2.0.M3]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.0.M3.jar:5.2.0.M3]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.0.M3.jar:5.2.0.M3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
```

I tryed different versions (1.11, 1.12, 1.13) with no results

Can you help me?

**Comment by AuligPromotions** [comment]
Yea same here, this issue started about 25 days ago but usually only lasts a day or so. Yesterday in the evening everything was fine for me, so i hope it'll be fine tomorrow again.

**Comment by heroys6** [comment]
Same problem. I have read in php/python instagram private api threads that they have same problems too.

**Comment by TLHP** [comment]
It lasts already 4 days for me. 
Last time it backed to work within someday. This time I don't know when :D

**Comment by lgfagundes** [comment]
Same here... any fixes?

**Comment by mostafa513** [comment]
I have same problem when i want to send post a photo

 Unrecognized token 'Something': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"Something is wrong. Please check your input and try again."; line: 1, column: 10]

**Comment by ruDmitry** [comment]
Same issue when sending image or video.

**Comment by Aulig** [comment]
Is it working again for you guys? Still broken for me.

**Comment by gss0** [comment]
Same here...

**Comment by ruDmitry** [comment]
Any news?

**Comment by TLHP** [comment]
> It lasts already 4 days for me.
> Last time it backed to work within someday. This time I don't know when :D

This time, it lasts like ... forever :D

**Comment by Aulig** [comment]
Judging from the commits and issues (for example https://github.com/mgp25/Instagram-API/issues/3057 ) on the php project posting is working for them again. Maybe we need to update our InstagramConstants.java? Their Constants file ( https://github.com/mgp25/Instagram-API/blob/adfa11e6d84ca070af82b43e7a5c73d2de8b7bcc/src/Constants.php ) is quite a bit more updated by now. Maybe someone who is using IG version 85 from #359 can mention if that makes any difference when posting images?

**Comment by pckz** [comment]
plox :(

**Comment by pckz** [comment]
plox :( same here

**Comment by ruDmitry** [comment]
What is the alternative of this library to java?

**Comment by zsouiki** [comment]
same here :(

**Comment by Raul-gupta** [comment]
guys is it working for anyone? Still broken for me.

**Comment by TLHP** [comment]
This repo is dead ...

**Comment by ruDmitry** [comment]
> This repo is dead ...

Is there an alternative to this repo?

**Comment by StacySiz** [comment]
same problem

**Comment by Aulig** [comment]
From the python library: 

> I think the endpoint is different.
> Look at node.js library (which is getting updated): https://github.com/dilame/instagram-private-api/blob/e2dadb32d55b26c3c9c4d94d64eedc1d01ad73cf/src/repositories/upload.repository.ts
> 
> Lines 20 and 21: const { body } = await this.client.request.send({
> url: `/rupload_igphoto/${name}`,
> 
> vs Python:
> 
> response = self.s.post(self.API_URL + "upload/photo/", data=m.to_string())
> 
> endpoint in nodejs library: /rupload_igphoto/
> endpoint in python library: upload/photo/
> 
> and it is getting 404 error in python because the endpoint does not exist anymore

The php library also seems to use this endpoint, but i think the endpoint is different from the standard api used in this library, as https://i.instagram.com/api/v1/rupload_igphoto/ results in a 404.
The php library seems to use "https://i.instagram.com/rupload_igphoto/". I'm not experienced enough with this repo to know how to best make this change here (as just changing getUrl in InstagramUploadPhotoRequest will give the first URL i mentioned), so maybe some of the experienced users like @brunocvcunha or @jvogit  can help.

**Comment by ruDmitry** [comment]
https://www.instagram.com/developer/
Instagram is moving to a new API. All old libraries are dying. We must either look for another way (Silenum for example) or wait until there are new libraries supporting the new API

**Comment by Aulig** [comment]
> 
> 
> https://www.instagram.com/developer/
> Instagram is moving to a new API. All old libraries are dying. We must either look for another way (Silenum for example) or wait until there are new libraries supporting the new API

I think thats the public api, while these inofficial libraries use the private one by pretending to be an android device. Aside from that, the php & node.js libraries are working fine after they made the change i mentioned above.

**Comment by jvogit** [comment]
Hi,

I looked into the issue, and I have successfully fixed the photo upload request. It is using the new endpoint per the php and node.js library. I just have to clean it up a bit, and make sure photo/album/story posting is fully working. I will make a pull request soon (as I am very busy!). 

For now, enjoy this gist for a quick fix.
https://gist.github.com/jvogit/a98b5e411ab7bc9a33a02d51267ac66c

Some remarks,
it has been tested for a single photo upload (not story or album currently as of this post)
the ig capabilities you can find them in the php library constants, or elsewhere. (you may also need to update constants overall, but I am planning to include these in my pull request)
this library is very much in need of refactoring/rewriting, something I'm planning to do once I have free time off of university.

**Comment by Aulig** [comment]
Thank you very much @jvogit, I really appreciate you taking the time to find a fix this quickly. Looking forward to the pull request!

**Comment by arezaiezr** [comment]
InstagramUploadPhotoRequest:

@Log4j
public class InstagramUploadPhotoRequest extends InstagramRequest<InstagramConfigurePhotoResult> {

	private File imageFile;

	private String caption;
	private String uploadId;

	@Override
	public String getUrl() {
		return "upload/photo/";
	}

	@Override
	public String getMethod() {
		return "POST";
	}

	public InstagramUploadPhotoRequest(File imageFile, String caption) throws IOException {
		this(imageFile, caption, null);
	}

	public InstagramUploadPhotoRequest(File imageFile, String caption, String uploadId) throws IOException {
		this.imageFile = imageFile;
		this.caption = caption;
		this.uploadId = uploadId;
	}

	@Override
	public InstagramConfigurePhotoResult execute() throws ClientProtocolException, IOException {

		if (uploadId == null) {
			uploadId = String.valueOf(System.currentTimeMillis());
		}

		HttpPost post = createHttpRequest();
		post.setEntity(createMultipartEntity());

		try (CloseableHttpResponse response = api.getClient().execute(post)) {
			api.setLastResponse(response);

			int resultCode = response.getStatusLine().getStatusCode();
			String content = EntityUtils.toString(response.getEntity());

			log.info("Photo Upload result: " + resultCode + ", " + content);

			post.releaseConnection();

			StatusResult result = parseResult(resultCode, content);

			if (!result.getStatus().equalsIgnoreCase("ok")) {
				throw new RuntimeException("Error happened in photo upload: " + result.getMessage());
			}


			InstagramConfigurePhotoResult configurePhotoResult = api.sendRequest(new InstagramConfigurePhotoRequest(MyImageUtils.getImage(imageFile), uploadId, caption));

			log.info("Configure photo result: " + configurePhotoResult);
			if (!configurePhotoResult.getStatus().equalsIgnoreCase("ok")) {
				throw new IllegalArgumentException("Failed to configure image: " + configurePhotoResult.getMessage());
			}

			StatusResult exposeResult = api.sendRequest(new InstagramExposeRequest());
			log.info("Expose result: " + exposeResult);
			if (!exposeResult.getStatus().equalsIgnoreCase("ok")) {
				throw new IllegalArgumentException("Failed to expose image: " + exposeResult.getMessage());
			}

			return configurePhotoResult;
		}
	}

	/**
	 * Creates required multipart entity with the image binary
	 *
	 * @return HttpEntity to send on the post
	 * @throws ClientProtocolException
	 * @throws IOException
	 */
	protected HttpEntity createMultipartEntity() throws ClientProtocolException, IOException {
		return new ByteArrayEntity(Files.readAllBytes(imageFile.toPath()));
	}

	protected String photoUploadParam() {
		final JSONObject jsonObject = new JSONObject();

		jsonObject.put("retry_context", "{ \"num_step_auto_retry\": 0, \"num_reupload\": 0, \"num_step_manual_retry\": 0 }");
		jsonObject.put("media_type", "1");
		jsonObject.put("upload_id", uploadId);
		jsonObject.put("image_compression", "{\"lib_name\":\"moz\",\"lib_version\":\"3.1.m\",\"quality\":\"95\"}");

		return jsonObject.toString();
	}

	/**
	 * Creates the Post Request
	 *
	 * @return Request
	 */
	protected HttpPost createHttpRequest() throws IOException {
		final String uploadIdHashCode = String.valueOf(imageFile.getName().hashCode());
		final String EntityName = uploadId + "_0_" + uploadIdHashCode;

		final String url = "https://i.instagram.com/rupload_igphoto/" + EntityName;
		log.info("URL Upload: " + url);

		HttpPost post = new HttpPost(url);
		post.addHeader("X-IG-Capabilities", "3Q4=");
		post.addHeader("X-IG-Connection-Type", "WIFI");
		post.addHeader("X-IG-APP-ID", "567067343352427");
		post.addHeader("X-Entity-Type", "image/jpeg");
		post.addHeader("Offset", "0");
		post.addHeader("X-Instagram-Rupload-Params", photoUploadParam());
		post.addHeader("X-Entity-Name", EntityName);
		post.addHeader("X-Entity-Length", String.valueOf(Files.readAllBytes(imageFile.toPath()).length));
		post.addHeader("X_FB_PHOTO_WATERFALL_ID", UUID.randomUUID().toString());
		post.addHeader("Accept-Language", "en-US");
		post.addHeader("User-Agent", InstagramConstants.USER_AGENT);
		post.addHeader("Content-Transfer-Encoding", "binary");
		post.addHeader("Content-Type", "application/octet-stream");

		return post;
	}

	@Override
	public InstagramConfigurePhotoResult parseResult(int statusCode, String content) {
		return parseJson(statusCode, content, InstagramConfigurePhotoResult.class);
	}
}

**Comment by arezaiezr** [comment]
InstagramUploadAlbumRequest:

	public class InstagramUploadAlbumRequest extends InstagramPostRequest<InstagramConfigureAlbumResult> {

    private List<File> imageList;

	private String caption;

	@Override
	public String getUrl() {
		return "upload/photo/";
	}

	@Override
	public String getMethod() {
		return "POST";
	}

	public interface ListFileRef extends Supplier<List<File>> {
	}

	public InstagramUploadAlbumRequest(ListFileRef imageFileList, String caption) throws IOException {
        this.imageList = imageFileList.get().stream().filter(Objects::nonNull).collect(Collectors.toList());
		this.caption = caption;
	}

	@Override
	public InstagramConfigureAlbumResult execute() throws ClientProtocolException, IOException {
		int count = 0;
		List<String> uploadIds = new LinkedList<>();
        for (File imageFile : imageList) {
            String uploadId = String.valueOf(System.currentTimeMillis());

            HttpPost post = createHttpRequest(imageFile, uploadId);
            post.setEntity(createMultipartEntity(imageFile));

			try (CloseableHttpResponse response = api.getClient().execute(post)) {
				api.setLastResponse(response);

				int resultCode = response.getStatusLine().getStatusCode();
				String content = EntityUtils.toString(response.getEntity());

				log.info("Photo Upload result: " + resultCode + ", " + content);

				post.releaseConnection();

				StatusResult result = parseResult(resultCode, content);

				if (!result.getStatus().equalsIgnoreCase("ok")) {
					throw new RuntimeException("Error happened in photo upload: " + result.getMessage());
				}
				uploadIds.add(uploadId);
			}
		}

		InstagramConfigureAlbumResult configurePhotoResult = api.sendRequest(new InstagramConfigureAlbumRequest(uploadIds, caption));

		System.out.println("Configure photo result: " + configurePhotoResult);
		if (!configurePhotoResult.getStatus().equalsIgnoreCase("ok")) {
			throw new IllegalArgumentException("Failed to configure image: " + configurePhotoResult.getMessage());
		}

		StatusResult exposeResult = api.sendRequest(new InstagramExposeRequest());
		System.out.println("Expose result: " + exposeResult);
		if (!exposeResult.getStatus().equalsIgnoreCase("ok")) {
			throw new IllegalArgumentException("Failed to expose image: " + exposeResult.getMessage());
		}

		return configurePhotoResult;

	}

	/**
	 * Creates required multipart entity with the image binary
	 *
	 * @return HttpEntity to send on the post
	 * @throws ClientProtocolException
	 * @throws IOException
	 */
    protected HttpEntity createMultipartEntity(File imageFile) throws ClientProtocolException, IOException {
        return new ByteArrayEntity(Files.readAllBytes(imageFile.toPath()));
    }

    protected String photoUploadParam(String uploadId) {
        final JSONObject jsonObject = new JSONObject();

        jsonObject.put("retry_context", "{ \"num_step_auto_retry\": 0, \"num_reupload\": 0, \"num_step_manual_retry\": 0 }");
        jsonObject.put("media_type", "1");
        jsonObject.put("upload_id", uploadId);
        jsonObject.put("image_compression", "{\"lib_name\":\"moz\",\"lib_version\":\"3.1.m\",\"quality\":\"95\"}");

        return jsonObject.toString();
	}

	/**
	 * Creates the Post Request
	 *
	 * @return Request
	 */
    protected HttpPost createHttpRequest(File imageFile, String uploadId) throws IOException {
        final String uploadIdHashCode = String.valueOf(imageFile.getName().hashCode());
        final String EntityName = uploadId + "_0_" + uploadIdHashCode;

        final String url = "https://i.instagram.com/rupload_igphoto/" + EntityName;
        log.info("URL Upload: " + url);

		HttpPost post = new HttpPost(url);
		post.addHeader("X-IG-Capabilities", "3Q4=");
		post.addHeader("X-IG-Connection-Type", "WIFI");
        post.addHeader("X-IG-APP-ID", "567067343352427");
        post.addHeader("X-Entity-Type", "image/jpeg");
        post.addHeader("Offset", "0");
        post.addHeader("X-Instagram-Rupload-Params", photoUploadParam(uploadId));
        post.addHeader("X-Entity-Name", EntityName);
        post.addHeader("X-Entity-Length", String.valueOf(Files.readAllBytes(imageFile.toPath()).length));
        post.addHeader("X_FB_PHOTO_WATERFALL_ID", UUID.randomUUID().toString());
		post.addHeader("Accept-Language", "en-US");
		post.addHeader("User-Agent", InstagramConstants.USER_AGENT);
        post.addHeader("Content-Transfer-Encoding", "binary");
        post.addHeader("Content-Type", "application/octet-stream");

		return post;
	}

	@Override
	public InstagramConfigureAlbumResult parseResult(int statusCode, String content) {
		return parseJson(statusCode, content, InstagramConfigureAlbumResult.class);
	}
	}

**Comment by taibhse-designs** [comment]
Ran into this problem while trying to get my social media manager program running again, cant upload image or album of images, can anyone run me through quickly whats needed to be done to fix this or when a fixed version will be out that I can update my program to use the new version?

**Comment by Aulig** [comment]
> Ran into this problem while trying to get my social media manager program running again, cant upload image or album of images, can anyone run me through quickly whats needed to be done to fix this or when a fixed version will be out that I can update my program to use the new version?

Just read the reply by jvogit above, I'm sure he will provide a reliable fix as soon as possible gor him.

**Comment by brunocvcunha** [comment]
Thanks @jvogit for finding a solution.

I am not able to put everything together and test at this time, but if you are willing to open a PR, I am more than happy to review and merge it.

**Comment by Mykke24** [comment]
I've found a working solution for uploading stories and timeline photos (not videos yet)


@Override
public String getUrl()
{
	return "rupload_igphoto/"; // new endpoint
	// return "upload/photo/"; // old endpoint 
}



@Override
public InstagramConfigurePhotoResult execute()
{
HttpPost post = null;
try
{
	post = createHttpRequest();
	// HttpEntity e = createMultipartEntity(uploadId); // YOU MUST REMOE THIS LINE 
// post.setEntity(e); // YOU MUST REMOE THIS LINE TOO
}
catch (IOException e2)
{
	// TODO Auto-generated catch block
	e2.printStackTrace();
}

.....

}



	/**
	 * Creates the Post Request
	 * 
	 * @return Request
	 */
	protected HttpPost createHttpRequest() throws IOException
	{
		// String url = InstagramConstants.API_URL + getUrl(); // old
		// ========= MINE
		// String url = "https://i.instagram.com/api/v1/" + getUrl();
		// Logger.log("URL Upload: " + url);
		//
		// HttpPost post = new HttpPost(url);
		// post.addHeader("X-IG-Capabilities", InstagramConstants.X_IG_Capabilities);
		// post.addHeader("X-IG-Connection-Type", "WIFI");
		// post.addHeader("Cookie2", "$Version=1");
		// post.addHeader("Accept-Language", InstagramConstants.postCountry);
		// post.addHeader("Accept-Encoding", "gzip, deflate");
		// post.addHeader("Connection", "close");
		// post.addHeader("Content-Type", "multipart/form-data; boundary=" + api.getUuid());
		// post.addHeader("User-Agent", InstagramConstants.getUserAgent(api.getUsername()));

		// ========= FROM NEW API
		String name = uploadId + "_0_" + ThreadLocalRandom.current().nextLong(1_000_000_000l, 9_000_000_000l);
		String url = "https://i.instagram.com/" + getUrl() + name;
		String param = String.format(
				"{ \"retry_context\":{ \"num_step_auto_retry\":0, \"num_reupload\":0, \"num_step_manual_retry\":0 }, \"media_type\":1, \"upload_id\":\"%s\", \"xsharing_user_ids\":[ ], \" image_compression\":{ \"lib_name\":\"moz\", \"lib_version\":\"3.1.m\", \"quality\":\"80\" } }",
				uploadId);
		log.info("URL Upload: " + url);
		HttpEntity ft = EntityBuilder.create().setBinary(this.bufferedImageToByteArray(bufferedImageFile)).setContentType(ContentType.APPLICATION_OCTET_STREAM).build();
		// HttpEntity ft = new FileEntity(file, ContentType.APPLICATION_OCTET_STREAM);
		HttpPost post = new HttpPost(url);
		post.addHeader("X-IG-Capabilities", InstagramConstants.X_IG_Capabilities);
		post.addHeader("X-IG-Connection-Type", "WIFI");
		post.addHeader("X-Instagram-Rupload-Params", param);
		post.addHeader("X_FB_WATERFALL_ID", api.getUuid() + "");
		post.addHeader("Cookie2", "$Version=1");
		post.addHeader("Accept-Language", "en-US");
		post.addHeader("Accept-Encoding", "gzip");
		post.addHeader("X-Entity-Name", name);
		post.addHeader("X-Entity-Type", "image/jpeg");
		post.addHeader("X-Entity-Length", ft.getContentLength() + "");
		post.addHeader("Offset", 0 + "");
		post.addHeader("Content-Type", "application/octet-stream");
		post.addHeader("User-Agent", InstagramConstants.getUserAgent(api.getUsername()));
		post.setEntity(ft);

		return post;
	}

**Comment by jvogit** [comment]
Hey all,

Sorry for delay! As I am very busy, it is hard to write, test, and validate code for long periods. 

I am happy to say that I've decided to improve the core functions of the library that were not working (and what I believed to be what this library is probably mainly used for). So far, I have gotten:

- Photo upload to work (including albums and stories!)
- Video upload to work
- Timeline feed and pagination (merging my previous PR #355 with new upcoming one)

These are what I believe to be the main core functionalities and I've worked to improve the library by making requests use headers, and overall improve the library without (hopefully) much breaking changes. The PR will be posted soon once I tidy up my work. You can see progress over at my fork of the repo.

I am grateful of other instagram private api (namely instagram-php and instagram node.js) for doing much of the hard work! Again, once I have proper time, I would like to rewrite the library to be more intuitive for users and be easier to manage and add new features as time goes.

**Comment by zsouiki** [comment]
Hi @jvogit ,

I just tested your fork, it works well ! (I only use the photo upload)

Thank you

**Comment by Aulig** [comment]
> 
> 
> Hi @jvogit ,
> 
> I just tested your fork, it works well ! (I only use the photo upload)
> 
> Thank you

Really? It's not working for me with commit 170f09d. Every Instagram request i send results in an error: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 606; received: 0)
Like not just the uploadphotorequest, but also login requests etc. Ill just wait for the PR i guess :)

**Comment by kabilya** [comment]
Still not working for me. Just built the latest 1.14-SNAPSHOT and still getting the Challenge required error and been logged out after calling login. Thanks.

**Comment by jvogit** [comment]
> Still not working for me. Just built the latest 1.14-SNAPSHOT and still getting the Challenge required error and been logged out after calling login. Thanks.

For challenge, I believe you must login. If there is challenge, suspend the program and then relogin with the verification code (or blank if you tap "This is Me" on your device). There is a method in the Instagram4j login that will take of type String which should be the code or an empty string.

**Comment by kabilya** [comment]
Thank @jvogit . I pulled the code from you forked version and it's working now. Thank you very much for your help.

**Comment by AleTassi** [comment]
Is this been fixed yet? I sow a merge request that should solve this issue #411 but I don't really know how git hub works

**Comment by Aulig** [comment]
It has been fixed @AleTassi, however you need to wait for the pull request to be merged to use it. If you need the fix right now, you can use jitpack to use this maven dependency:
`        <dependency>
            <groupId>com.github.jvogit</groupId>
            <artifactId>instagram4j</artifactId>
            <version>5b23dd9</version>
        </dependency>`

this also requires this repository
 `        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>`

(all of this belongs in your pom.xml file)
