### ISSUE TITLE
Massive increase in Jar file size

### ISSUE THREAD

**Issue by NandanDesai** [brunocvcunha/instagram4j#398]
While building the Jar file, the size is extremely massive. It's around 200 MB. How reduce the JAR file size?

**Comment by mostafa513** [comment]
I'm facing the same problem. I think this problem occurred by adding "OpenCV" and "FFmpeg" library. How I can remove them?

**Comment by NandanDesai** [comment]
I cloned this entire library, changed the Apache HttpClient library to OkHttp so that it will be Android friendly and extracted only those Classes which I actually require for my use case and discarded the rest of the Classes from the library. So the final "modified" library JAR file is roughly 1.5 MB now. I used only 2 dependencies. OkHttp and Jackson (for parsing JSON). I removed all the other unnecessary dependencies that I didn't wanted.
