### ISSUE TITLE
can't send direct message 

### ISSUE THREAD

**Issue by mehhrad** [brunocvcunha/instagram4j#41]
i want to send a direct message.
what is receipents? usernames?
my code:

`ArrayList<String> list = new ArrayList<>();
            list.add("a_username");
            instagram.sendRequest(InstagramDirectShareRequest
                    .builder(InstagramDirectShareRequest.ShareType.MESSAGE,list)
                    .message("sent from instajj")
                    .build());`

then i get this Exception:
 `java.lang.NoClassDefFoundError: lombok/Lombok`

i added 
`compile 'org.projectlombok:lombok:1.14.4'` to dependencies
then i get this Exeption:

`com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Oops': was expecting ('true', 'false' or 'null')
 at [Source: Oops, an error occurred.`

**Comment by Mykke24** [comment]
I get the exact same error.
"Oops, an error occurred."

Working on it since a few hours but can't solve it

**Comment by BondarenkoEvgeny** [comment]
> what is receipents? usernames?
receipents is a list of recipients IDs (i.e. "1234567890")

**Comment by Mykke24** [comment]
Yes @BondarenkoEvgeny right, its an ID not the username
Use the pk Attribute in users object

**Comment by brunocvcunha** [comment]
Looks like everything is ok

Thanks guys!
