### ISSUE TITLE
Anyone else experiencing a lot of "Premature end of Content-Length delimited message body"?

### ISSUE THREAD

**Issue by GetsEclectic** [brunocvcunha/instagram4j#416]
I've started getting a lot of these errors lately, they seem to be all or mostly when getting the likers for a post, especially if the post has a lot of likes.

I saw this error mentioned in another issue:
https://github.com/brunocvcunha/instagram4j/issues/393
so I tried jvogit's fork to see if that fixed it, but it didn't seem to make a difference.

`
javax.net.ssl.SSLException: Connection reset
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 33457; received: 16384
`

**Comment by Aulig** [comment]
I used to get that error in an old version of jvogits fork, but he has already fixed it. Without further knowledge Id assume this is a problem with your internet connection, especially if its just occuring "randomly".
