### ISSUE TITLE
Lombok error?

### ISSUE THREAD

**Issue by patriotaki** [brunocvcunha/instagram4j#51]
![img_2155](https://user-images.githubusercontent.com/22542586/29733477-f101be2c-89f5-11e7-9f7d-002be9074154.PNG)

Check this error .
In trying to login,search for usernMes and then block them

**Comment by brunocvcunha** [comment]
How did you generate the JAR to run? Are you including lombok dependencies?

**Comment by patriotaki** [comment]
Ye i build the jar with all the jars in the lib folder

**Comment by patriotaki** [comment]
any news on that?

**Comment by brunocvcunha** [comment]
This is clearly some problem importing lombok dependencies (or not including it in your classpath). I suggest using Maven to manage it. There's a sample in issue #1.

**Comment by vbudilov** [comment]
I just got the same exception, while running a for loop to get the followers of a user.
