### ISSUE TITLE
How can i get the media id of photo i just uploaded using instagramUploadPhotoRequest

### ISSUE THREAD

**Issue by captainJackBard** [brunocvcunha/instagram4j#6]
Hello, Is it possible to get the media id of the photo uploaded as part of the return value of instagramUploadPhotoRequest?

**Comment by brunocvcunha** [comment]
Now it is :) 

instagramUploadPhotoRequest returns InstagramConfigurePhotoResult, that contains upload_id and the "media" property (InstagramFeedItem).

Thanks!

**Comment by brunocvcunha** [comment]
Fixed on master, will be deployed soon / after some more integrated tests.
