### ISSUE TITLE
 No content to map due to end-of-input

### ISSUE THREAD

**Issue by mehhrad** [brunocvcunha/instagram4j#60]
i get this exception after some api calls ...

`Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
W/System.err:  at [Source: ; line: 1, column: 0]
W/System.err:     at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3838)
W/System.err:     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
W/System.err:     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
W/System.err:     at dev.niekirk.com.instagram4android.requests.InstagramRequest.parseJson(InstagramRequest.java:112)
W/System.err:     at dev.niekirk.com.instagram4android.requests.InstagramRequest.parseJson(InstagramRequest.java:98)
W/System.err:     at dev.niekirk.com.instagram4android.requests.InstagramGetUserFollowersRequest.parseResult(InstagramGetUserFollowersRequest.java:35)
W/System.err:     at dev.niekirk.com.instagram4android.requests.InstagramGetUserFollowersRequest.parseResult(InstagramGetUserFollowersRequest.java:14)
W/System.err:     at dev.niekirk.com.instagram4android.requests.InstagramGetRequest.execute(InstagramGetRequest.java:42)
W/System.err:     at dev.niekirk.com.instagram4android.Instagram4Android.sendRequest(Instagram4Android.java:195)`

 what does it mean? 

how to avoid it ?

 and how to react ?(logging again?)

**Comment by brunocvcunha** [comment]
I think you should get support here: https://github.com/charlieAndroidDev/Instagram4Android
