### ISSUE TITLE
Handling a non-existing user PKID

### ISSUE THREAD

**Issue by mike75rock** [brunocvcunha/instagram4j#7]
Hi,

If a user deleted or changed their account, so that the PKID doesn't exist any longer, the follow/unfollow request fail with an exception (not a vaild Json).

`Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')`

The response that the site returns is an HTML source code with "Page Not Found".

The exception happens in classes InstagramFollowRequest and InstagramUnfollowRequest.
```
@Override
    @SneakyThrows
    public StatusResult parseResult(int statusCode, String content) {
        return parseJson(content, StatusResult.class);
    }
```
Please let me know if you need more info.
Great library!
Thanks.

**Comment by brunocvcunha** [comment]
Fixed on master, will be deployed soon / after some more integrated tests.

Thanks!

**Comment by mike75rock** [comment]
Cool! Thanks. Did you commit to master? I can help to test it.

**Comment by brunocvcunha** [comment]
Yes, fixed on master. Thanks @mike75rock

**Comment by mike75rock** [comment]
Hi, Bruno. When do you think you will release 1.2? :)

**Comment by brunocvcunha** [comment]
Released! Thanks
