### ISSUE TITLE
Unlike Media/Post

### ISSUE THREAD

**Issue by rahulserver** [brunocvcunha/instagram4j#70]
I could not find an InstagramUnlikeRequest to unlike a post. This feature will be great to have!

Or is there already a way to unlike a media ?

**Comment by patriotaki** [comment]
maybe try to like same photo twice?
see if it removes it

**Comment by rahulserver** [comment]
I don't think it should work because on the instagram web, the endpoint invoked for the unlike is different from that for the like operation. 
But still will try @patriotaki

**Comment by rahulserver** [comment]
I think it should not be a difficult task to have the unlike operation. We just need to replace the /like with /unlike in the endpoint. 
Although I am not sure about the response parsing. @brunocvcunha
