### ISSUE TITLE
How do I reuse the login session? 

### ISSUE THREAD

**Issue by vbudilov** [brunocvcunha/instagram4j#71]
I'm trying to understand what I need to cache/save in order to persist a user login. Basically, what do I need to save after I run the following?

        this.instagram = Instagram4j.builder().username(username).password(password).build()
        instagram.setup()
        instagram.login()

Are there any tokens/cookies that are returned that I can save and reuse? I want to avoid logging in the user with every single request. 

Thanks!

**Comment by brunocvcunha** [comment]
Yes, it uses cookies. Maybe we could make Instagram4j serializable and you can serialize the whole instance into a file/database and read it back later. Will do some tests on this.

**Comment by brunocvcunha** [comment]
Yes, it uses cookies, plus the UUID has to be stored to match the next requests.

I'll try some things. But I think the easiest way would be to allow passing a custom cookie store when you call the `setup()`, we always initialize a new one:
`this.client.setCookieStore(new BasicCookieStore());`

Making the whole Instagram4j serializable may work too, but need to run some tests on this.

**Comment by vbudilov** [comment]
Thanks exactly what I thought about -- if we can pass in a cookie store then that cookie store can be sent back to a client and it can pass it to the backend whenever instagram needs to be accessed. Thanks a lot!

**Comment by brunocvcunha** [comment]
Hi @vbudilov,

Seems to be working fine, here's a way that worked for me, by serializing the CookieStore to a file (but you can retrieve it from wherever you want).


```
        Instagram4j instagram = Instagram4j.builder().username(USERNAME).password(PASSWORD).build();
        instagram.setup();
        instagram.login();
        
        File cookiesFile = new File(USERNAME + ".txt");
        ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(cookiesFile));
        oos.writeObject(instagram.getCookieStore());
        oos.close();
        
        
        ObjectInputStream ois = new ObjectInputStream(new FileInputStream(cookiesFile));
        CookieStore cookieStore = (CookieStore) ois.readObject();
        ois.close();
        
        Instagram4j instagram2 = Instagram4j.builder().username(USERNAME)
                .password(PASSWORD)
                .uuid(instagram.getUuid())
                .cookieStore(cookieStore)
                .build();
        instagram2.setup();
        
        InstagramGetMediaLikersResult tagFeed = instagram2.sendRequest(new InstagramGetMediaLikersRequest(1020304050L));
```

**Comment by erfankm7** [comment]
it has some bug : my revived message is : 

InstagramRequest:126 - Reading InstagramGetUserFollowersResult from {"sections": null, "users": [], "big_list": false, "next_max_id": null, "page_size": 200, "status": "OK"}

and 


Instagram4j:283 - Result for org.brunocvcunha.instagram4j.requests.InstagramGetUserFollowingRequest: InstagramGetUserFollowersResult(super=StatusResult(status=OK, message=null, spam=false, lock=false, feedback_title=null, feedback_message=null, error_type=null, checkpoint_url=null), big_list=false, next_max_id=null, page_size=200, users=[])

**Comment by jemand771** [comment]
i don't think this has anything to do with the login. can you post your code? (and not just the error message)

**Comment by erfankm7** [comment]
> i don't think this has anything to do with the login. can you please post your code? (and not just the error message)

```
Instagram4j instagram = Instagram4j.builder().username("username").password("password").build();
instagram.setup();
instagram.login();
```
this is my code , but after 5 or 6 times login or do some task like getFollower  , your original instagram app logout you !

**Comment by jemand771** [comment]
Getting Followers and Followings are "expensive" requests, I think. Sometimes you may get tempbanned or logged out if you send too many requests too quickly. Add delays to your code or try storing your received data (instead of re-requesting it everytime)

If you are asked to verify your account with your email address, #339 might be worth looking into for you. (Note that this is currently not part of the official stable version of this library)

Also, there will be a better way to access Followers/Followings in a future version. #363
