### ISSUE TITLE
Delete media

### ISSUE THREAD

**Issue by mike75rock** [brunocvcunha/instagram4j#72]
Is it possible to delete media?
If not, can this be added?

Thanks.

**Comment by brunocvcunha** [comment]
Added the InstagramDeleteMediaRequest (still on master, not released yet).

**Comment by mike75rock** [comment]
Thank you!

**Comment by ChrisJSt** [comment]
Hello, when is the next release going to take place ?

**Comment by brunocvcunha** [comment]
Done, thanks guys
