### ISSUE TITLE
Push New Version

### ISSUE THREAD

**Issue by ChrisJSt** [brunocvcunha/instagram4j#74]
Hello, would it be possible to push the new 1.5 version to maven ?

Thanks

**Comment by krismorte** [comment]
In this link has most recently version according Bruno

https://oss.sonatype.org/content/repositories/snapshots/org/brunocvcunha/instagram4j/instagram4j/1.3-SNAPSHOT/

**Comment by brunocvcunha** [comment]
Done, thanks guys
