### ISSUE TITLE
Status Result: Action Blocked

### ISSUE THREAD

**Issue by jumaskow** [brunocvcunha/instagram4j#77]
Hi,
when I try to like a media, the following Status result comes up:

FeedBack Title: "Action Blocked"
FeedBack Message: "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us of you think we made a mistake."
Message: feedback_required
Status: fail

**Comment by ChrisJSt** [comment]
You likely exceed the action limit thats set by Instagram. Try to mimic a human

**Comment by brunocvcunha** [comment]
There's another post that gives some details about it: #19
