### ISSUE TITLE
Implementation problem gradle 3.0.0

### ISSUE THREAD

**Issue by jackaru** [brunocvcunha/instagram4j#80]
![image](https://user-images.githubusercontent.com/21238513/32455227-e1bab36e-c321-11e7-9a9b-7d85e887374f.png)

When I test the app, this problem appear. I've tried excluding dependencies / license and more but other problems appear.  
(I'm using Android Studio 3)

**Comment by brunocvcunha** [comment]
Hi!

For Android, please refer to #5
