### ISSUE TITLE
app:transformResourcesWithMergeJavaResForDebug when try to compile

### ISSUE THREAD

**Issue by Miljan9602** [brunocvcunha/instagram4j#83]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'log4j.properties' 

How to fix this ? I made new project to test this library, so this is the only library i use.

**Comment by brunocvcunha** [comment]
Is it Android? There are a few issues in this repo that talk about Android and a project fork to support it.

**Comment by Miljan9602** [comment]
Yeah, is it android

**Comment by jackaru** [comment]
Same problem

**Comment by brunocvcunha** [comment]
Closing this, please check #5

**Comment by cemocanon** [comment]
same problem .s
