### ISSUE TITLE
this is not really a issue but more of a question

### ISSUE THREAD

**Issue by thatmadhacker** [brunocvcunha/instagram4j#84]
So i was wondering if there is a way to direct message people using this api, i looked through the code briefly and didnt see anything so how would i do this?

**Comment by krismorte** [comment]
I used this and works well
```
recipients - List of recipients IDs (i.e. "1234567890")
instagram.sendRequest(InstagramDirectShareRequest.builder(ShareType.MESSAGE, recipients).message(message).build());
```

**Comment by brunocvcunha** [comment]
That's right, thanks @krismorte
