### ISSUE TITLE
gradle build 

### ISSUE THREAD

**Issue by rasoolta** [brunocvcunha/instagram4j#86]
when i use instagram4j api get error gradle sync
errors is 
 More than one file was found with OS independent path 'META-INF/DEPENDENCIES'
 More than one file was found with OS independent path 'log4j.properties'
 More than one file was found with OS independent path 'org/bytedeco/javacpp/macosx-x86_64/libusb-1.0.dylib'
i fix errors with this code in gradle
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'log4j.properties'
        exclude 'org/bytedeco/javacpp/macosx-x86_64/libusb-1.0.dylib'
    }
after this solution i get this errors

Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\RasoolTA.DESKTOP-0JFVKI1\.gradle\caches\modules-2\files-2.1\org.brunocvcunha.instagram4j\instagram4j\1.5\ec74a4b62a54f3cd8314bfbc6b0f866bf638cffd\instagram4j-1.5.jar

Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing org/brunocvcunha/instagram4j/Instagram4j.class

Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)

Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\RasoolTA.DESKTOP-0JFVKI1\.gradle\caches\modules-2\files-2.1\org.brunocvcunha.instagram4j\instagram4j\1.5\ec74a4b62a54f3cd8314bfbc6b0f866bf638cffd\instagram4j-1.5.jar

**Comment by brunocvcunha** [comment]
For Android, we have this library supporting https://github.com/charlieAndroidDev/Instagram4Android
