### ISSUE TITLE
How to get users i following ?

### ISSUE THREAD

**Issue by jvitorr** [brunocvcunha/instagram4j#89]
There is something like  InstagramGetUserFollowingResult ?

**Comment by rasoolta** [comment]
please hep me
How did you sync this libarary (instagram4j)?
I try to build this lib in android stadio, But I did not succeed 😞😞
pease help me to build this lib
can you send gradle file for me
please help ....

**Comment by jvitorr** [comment]
See this https://github.com/brunocvcunha/instagram4j/issues/5

**Comment by ozankaraali** [comment]
```
InstagramGetUserFollowersResult Following = instagram.sendRequest(new InstagramGetUserFollowingRequest(userResult.getUser().getPk()));
List<InstagramUserSummary> users = Following.getUsers();
```

**Comment by sam253narula** [comment]
ozankaraali  bro your code is correct but its not pulling the entire list of following. any idea how can I pull the entire list?

**Comment by ozankaraali** [comment]
@sam253narula you need to use pagination with last pkid that returned
