### ISSUE TITLE
Comments do not contain like count

### ISSUE THREAD

**Issue by alinafariyeh** [brunocvcunha/instagram4j#92]
I have noticed that the posts comments do not contain the comment like count. Is there any timeline for fixing this?
Can anyone guide about how to fix it?

**Comment by ozankaraali** [comment]
On InstagramPostCommentResult; you need to define a: private ArrayList<InstagramUser> users; (that I don't test), which included my pull request. Hopefully it will help.

**Comment by IslamNosser** [comment]
Hi, I cannot manage to get the likes per comment using InstagramGetMediaCommentsResult. Do you have any recommendations?
