### ISSUE TITLE
InstagramGetFriendshipsRequest returning invalid parameters error?

### ISSUE THREAD

**Issue by MaTrIxProgram** [brunocvcunha/instagram4j#99]
hi
i used the code down below to check if i am following some people who are followed by another person
` List<Long> topflwrs = new ArrayList<Long>();
for (int i = 0; i < config.getFollowcount(); i++) {
topflwrs.add(targetfollowers.get(i).getPk());
}
InstagramGetFriendshipsResult res = instagram.sendRequest(new 
   InstagramGetFriendshipsRequest(topflwrs));
`
but when i use this if statement : 
` if (!res.getFriendship_statuses().get(i).isFollowing())`

it throws a NullPointerException

which is caused by 

`{"message": "Invalid parameters", "status": "fail"}
[01:23:34 INFO]:InstagramGetFriendshipsResult(super=StatusResult(status=fail, message=Invalid parameters, spam=false, lock=false, feedback_title=null, feedback_message=null, error_type=null, checkpoint_url=null), friendship_statuses=null)`

i guess there must be an issue in InstagramGetFriendshipsRequest / Result class.

thanks

**Comment by MaTrIxProgram** [comment]
any updates?

**Comment by MaTrIxProgram** [comment]
Seems to be fixed in 1.6 update . thanks for your awesome repository :D have a good day

**Comment by melihculha** [comment]
Same problem any solution?

**Comment by jessrix** [comment]
Have you tried updating the library to latest release?

**Comment by melihculha** [comment]
yes I have
